import type { Metadata } from 'next';

import { Google_Sans, Google_Sans_Flex } from 'next/font/google';

import './globals.css';

const googleSans = Google_Sans({
  variable: '--font-google-sans',
  subsets: ['latin'],
});

const googleSansFlex = Google_Sans_Flex({
  variable: '--font-google-sans-flex',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Reyz.ai',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSans.variable} ${googleSansFlex.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
